config:
  processing_strategy: pointer
  labels: 
    0: "0"
    1: "1"
  type: "Instance Segmentation" 
  shapes: [1, 3, 640, 640]

inputs:
  - name: "image"
    description: "The image can be a valid URL or a Base64 encoded data URI." # Updated
    type: "string"
    format: "uri | base64"
    required: true
    
  - name: "conf_threshold"
    description: "Optional. Confidence threshold (only detections with confidence ≥ this value will be kept)." # Updated
    type: "float"
    required: false
    default: 0.25
    minimum: 0.0
    maximum: 1.0

  - name: "nms_threshold"
    description: "Optional. NMS (Non-Maximum Suppression) threshold (boxes with IoU > this value will be suppressed)." # Updated
    type: "float"
    required: false
    default: 0.45
    minimum: 0.0
    maximum: 1.0
    
  - name: "scale_min"
    description: "Information about the measurement range start point." # Updated from "量程起点信息"
    type: "float"
    required: true
    default: 0.0
    # Note: minLength/maxLength are usually not applicable to type: "float", 
    # and typically apply to string/array types. Keeping them as-is but noting discrepancy.
    minLength: 4
    maxLength: 4

  - name: "scale_max"
    description: "Information about the measurement range end point." # Updated from "量程终点信息"
    type: "float"
    required: true
    default: 60.0
    # Note: minLength/maxLength are usually not applicable to type: "float".
    minLength: 4
    maxLength: 4

outputs:
  - name: "data"
    description: "A list of detection results for single or multiple images, where each element corresponds to one image and its detected objects." # Updated
    type: "array"
    required: true
    items:
      description: "Describes a single image and its detection results." # Updated
      type: "object"
      required: true
      properties:
        file_name:
          description: "Identifier or name of the recognized file." # Updated
          type: "string"
          required: true
        detections:
          description: "All objects detected in this image." # Updated
          type: "array"
          items:
            type: "object"
            properties:
              boxes:
                type: "array"
                description: "Detection box coordinates [x, y, w, h]." # Updated
                items:
                  type: "integer"
                minLength: 4
                maxLength: 4
              conf:
                description: "Confidence score (0.0 to 1.0)." # Updated
                type: "float"
                required: true
              cls:
                description: "Identified class label (e.g., '0', 'person', 'dog')." # Updated
                type: "string"
                required: true
              masks:
                type: "array"
                description: "Optional: List of segmentation contour coordinates, where each subarray is a vertex [x, y] representing a point on the contour." # Updated
                items:
                  type: "array"
                  minItems: 2
                  maxItems: 2
                  items:
                    type: "integer"
                    description: "Pixel coordinate, non-negative integer." # Updated
                    minimum: 0
              points:
                type: "array"
                description: "Optional: List of keypoints for a pose model, each keypoint is [x, y, id, confidence]." # Updated
                items:
                  type: "array"
                  description: "x and y are pixel coordinates (float), id is the keypoint index (integer), and confidence is the confidence score (float)." # Updated
                  minItems: 4
                  maxItems: 4
              skeleton:
                type: "array"
                description: "List of skeletal connection data, each element is a pair of keypoint indices [idx1, idx2], returned along with 'points'." # Updated
                items:
                  type: "array"
                  description: "A single skeletal connection consists of two keypoint indices." # Updated
                  items:
                    type: "integer"
                    description: "Keypoint index." # Updated
                  minItems: 2
                  maxItems: 2