config:
  processing_strategy: generic
  labels: 
    0: 'person'
    1: 'bicycle'
    2: 'car'
    3: 'motorcycle'
    4: 'airplane'
    5: 'bus'
    6: 'train'
    7: 'truck'
    8: 'boat'
    9: 'traffic light'
    10: 'fire hydrant'
    11: 'stop sign'
    12: 'parking meter'
    13: 'bench'
    14: 'bird'
    15: 'cat'
    16: 'dog'
    17: 'horse'
    18: 'sheep'
    19: 'cow'
    20: 'elephant'
    21: 'bear'
    22: 'zebra'
    23: 'giraffe'
    24: 'backpack'
    25: 'umbrella'
    26: 'handbag'
    27: 'tie'
    28: 'suitcase'
    29: 'frisbee'
    30: 'skis'
    31: 'snowboard'
    32: 'sports ball'
    33: 'kite'
    34: 'baseball bat'
    35: 'baseball glove'
    36: 'skateboard'
    37: 'surfboard'
    38: 'tennis racket'
    39: 'bottle'
    40: 'wine glass'
    41: 'cup'
    42: 'fork'
    43: 'knife'
    44: 'spoon'
    45: 'bowl'
    46: 'banana'
    47: 'apple'
    48: 'sandwich'
    49: 'orange'
    50: 'broccoli'
    51: 'carrot'
    52: 'hot dog'
    53: 'pizza'
    54: 'donut'
    55: 'cake'
    56: 'chair'
    57: 'couch'
    58: 'potted plant'
    59: 'bed'
    60: 'dining table'
    61: 'toilet'
    62: 'tv'
    63: 'laptop'
    64: 'mouse'
    65: 'remote'
    66: 'keyboard'
    67: 'cell phone'
    68: 'microwave'
    69: 'oven'
    70: 'toaster'
    71: 'sink'
    72: 'refrigerator'
    73: 'book'
    74: 'clock'
    75: 'vase'
    76: 'scissors'
    77: 'teddy bear'
    78: 'hair drier'
    79: 'toothbrush'
  type: "Object Detection" # Updated from "目标识别"
  shapes: [1, 3, 640, 640]
  post_format:
    - "concatLabels"

inputs:
  - name: "image"
    description: "The image can be a valid URL or a Base64 encoded data URI." # Updated
    type: "string"
    format: "uri | base64"
    required: true
    
  - name: "conf_threshold"
    description: "Optional. Confidence threshold (only detections with confidence ≥ this value will be kept)." # Updated
    type: "float"
    required: false
    default: 0.25
    minimum: 0.0
    maximum: 1.0

  - name: "nms_threshold"
    description: "Optional. NMS (Non-Maximum Suppression) threshold (boxes with IoU > this value will be suppressed)." # Updated
    type: "float"
    required: false
    default: 0.45
    minimum: 0.0
    maximum: 1.0

outputs:
  - name: "data"
    description: "A list of detection results for single or multiple images, where each element corresponds to one image and its detected objects." # Updated
    type: "array"
    required: true
    items:
      description: "Describes a single image and its detection results." # Updated
      type: "object"
      required: true
      properties:
        file_name:
          description: "Identifier or name of the recognized file." # Updated
          type: "string"
          required: true
        detections:
          description: "All objects detected in this image." # Updated
          type: "array"
          items:
            type: "object"
            properties:
              boxes:
                type: "array"
                description: "Detection box coordinates [x, y, w, h]." # Updated
                items:
                  type: "integer"
                minLength: 4
                maxLength: 4
              conf:
                description: "Confidence score (0.0 to 1.0)." # Updated
                type: "float"
                required: true
              cls:
                description: "Identified class label (e.g., '0', 'person', 'dog')." # Updated
                type: "string"
                required: true
              masks:
                type: "array"
                description: "Optional: List of segmentation contour coordinates, where each subarray is a vertex [x, y] representing a point on the contour." # Updated
                items:
                  type: "array"
                  minItems: 2
                  maxItems: 2
                  items:
                    type: "integer"
                    description: "Pixel coordinate, non-negative integer." # Updated
                    minimum: 0
              points:
                type: "array"
                description: "Optional: List of keypoints for a pose model, each keypoint is [x, y, id, conf]." # Updated
                items:
                  type: "array"
                  description: "x and y are pixel coordinates (float), id is the keypoint index (integer), and conf is the confidence score (float)." # Updated
                  minItems: 4
                  maxItems: 4
              skeleton:
                type: "array"
                description: "List of skeletal connection data, each element is a pair of keypoint indices [idx1, idx2], returned along with 'points'." # Updated
                items:
                  type: "array"
                  description: "A single skeletal connection consists of two keypoint indices." # Updated
                  items:
                    type: "integer"
                    description: "Keypoint index." # Updated
                  minItems: 2
                  maxItems: 2